# Generated by Django 5.2.8 on 2025-11-24 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password_hash', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apostilas.user')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apostilas.role')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pedido', models.DateTimeField()),
                ('apostila', models.CharField(max_length=255)),
                ('nome_aluno', models.CharField(max_length=255)),
                ('dk', models.IntegerField()),
                ('turma', models.CharField(max_length=100)),
                ('horario', models.TimeField()),
                ('impressa', models.BooleanField(default=False)),
                ('entregue', models.BooleanField(default=False)),
                ('data_impressao', models.DateTimeField(blank=True, null=True)),
                ('data_entrega', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arquivado', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apostilas.user')),
            ],
        ),
    ]
